/**
 * Embedded ERP Surface — Content Security Policy middleware.
 *
 * Single source of truth for CSP headers on every embedded route AND for the
 * static `/embedded/session-expired.html` interstitial. Mounted in
 * src/middleware/setup/RouteSetup.ts alongside the dynamic embedded handlers.
 * NEVER serve embedded content via Express's default static middleware — that
 * would bypass this gate.
 *
 * The hash region is regenerated by scripts/generate-embedded-csp.mjs (runs
 * as `prebuild` and as the pre-commit hook on bootstrap-script changes) and
 * verified by scripts/check-embedded-csp-hash.mjs in CI.
 */
import type { Request, Response, NextFunction } from 'express';
import { createHash } from 'node:crypto';

// BEGIN GENERATED CONSTANTS
// AUTO-GENERATED by scripts/generate-embedded-csp.mjs — do not hand-edit.
// Re-run via `npm run generate:embedded-csp`.
export const EMBEDDED_BOOTSTRAP_SHA256 = 'sha256-PYIya0fb3hsnd8prTTQ5FT+AsLuld5hYUsij3UET+zQ=';
// END GENERATED CONSTANTS

// Inline body of the session-expired Reload-button handler. Extracted to a
// constant so we can compute its sha256 at module load and add it to the
// CSP `script-src` allowlist. Closes Copilot review round-2 BLOCKS-MERGE #3:
// without the hash, the inline <script> in SESSION_EXPIRED_HTML was blocked
// by `script-src 'self' '${EMBEDDED_BOOTSTRAP_SHA256}'` and the Reload
// button's postMessage handler never ran in production.
const SESSION_EXPIRED_SCRIPT_BODY = `
      (function () {
        var btn = document.getElementById('reload-btn');
        btn.addEventListener('click', function () {
          if (window.parent && window.parent !== window) {
            try {
              window.parent.postMessage({ type: 'embedded:session-recovery-requested' }, '*');
              return;
            } catch (e) { /* fall through to standalone reload */ }
          }
          window.location.reload();
        });
      })();
    `;

export const EMBEDDED_SESSION_EXPIRED_SCRIPT_SHA256 =
  'sha256-' +
  createHash('sha256').update(SESSION_EXPIRED_SCRIPT_BODY).digest('base64');

/**
 * `frame-ancestors` is the gate — only NetSuite or BC origins can embed.
 * Future allowlist additions require ADR-018 + reviewer sign-off.
 *
 * `script-src` carries TWO hashes: the guest-bootstrap.js for embedded
 * module pages AND the inline session-expired-reload handler so the
 * recovery UI works in production.
 *
 * Note: when this constant changes, tests/unit/embedded/csp-header.test.ts
 * will fail (exact-string drift tripwire). Re-stamp deliberately.
 */
export const EMBEDDED_CSP_POLICY: string =
  "default-src 'self'; " +
  "frame-ancestors https://*.netsuite.com https://*.dynamics.com; " +
  `script-src 'self' '${EMBEDDED_BOOTSTRAP_SHA256}' '${EMBEDDED_SESSION_EXPIRED_SCRIPT_SHA256}'; ` +
  "style-src 'self' 'unsafe-inline'; " +
  "connect-src 'self'";

// Inline HTML body for the session-expired interstitial. Closes Copilot
// review BLOCKS-MERGE #3 (round 1): inlining as a TS template literal
// eliminates BOTH the static-middleware bypass AND the tsc-doesn't-copy-
// HTML-to-dist runtime path issue. The Reload button uses postMessage so
// the host adapter (NetSuite Suitelet, BC AL Extension) can perform
// recovery — closes Copilot review BLOCKS-MERGE #4 (round 1).
const SESSION_EXPIRED_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Session ended — SuiteCentral</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 2rem; background: #f8fafc; color: #1f2937; }
      .card { max-width: 420px; margin: 4rem auto; background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 2rem; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08); }
      h1 { font-size: 1.25rem; margin: 0 0 0.75rem; }
      p { margin: 0 0 1.25rem; line-height: 1.5; }
      button.reload { display: inline-block; background: #2563eb; color: #ffffff; border: 0; cursor: pointer; font: inherit; padding: 0.5rem 1rem; border-radius: 6px; font-weight: 500; }
      button.reload:hover { background: #1d4ed8; }
    </style>
  </head>
  <body>
    <main class="card">
      <h1>Session ended</h1>
      <p>Your embedded session is no longer active. Reload to restart a fresh session inside your ERP.</p>
      <button class="reload" id="reload-btn" type="button">Reload</button>
    </main>
    <script>${SESSION_EXPIRED_SCRIPT_BODY}</script>
  </body>
</html>`;

/**
 * Apply the embedded CSP policy to every response on routes this middleware
 * is mounted on. Idempotent: setHeader overwrites prior values from upstream
 * helmet/CSP middleware.
 */
export function embeddedCspMiddleware(
  _req: Request,
  res: Response,
  next: NextFunction,
): void {
  res.setHeader('Content-Security-Policy', EMBEDDED_CSP_POLICY);
  next();
}

/**
 * Static handler for `/embedded/session-expired.html`. Mounted via the
 * embedded route group so it inherits embeddedCspMiddleware. MUST NOT be
 * served by Express's default static middleware.
 *
 * Cache headers (closes round-8 finding #4): no-store + no-cache so neither
 * browsers nor intermediary CDNs cache this asset — it's part of the
 * session-recovery path; a stale copy could replay an old session boundary.
 */
export function sessionExpiredHandler(
  _req: Request,
  res: Response,
): void {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate');
  res.setHeader('Pragma', 'no-cache');
  res.status(200).send(SESSION_EXPIRED_HTML);
}
