export const AUTH_CONSTANTS = {
  JWT_SECRET_MIN_LENGTH: 32,
  JWT_SECRET_PRODUCTION_MIN_LENGTH: 64, // Enhanced security for production
  TOKEN_CLEANUP_INTERVAL_MS: 30 * 60 * 1000, // 30 minutes
  TOKEN_EXPIRY_BUFFER_MS: 5 * 60 * 1000, // 5 minutes
  TOKEN_CLEANUP_BUFFER_MS: 60 * 60 * 1000, // 1 hour
  BCRYPT_SALT_ROUNDS: 12,
  DEFAULT_TOKEN_EXPIRES_IN: '24h',
  OAUTH2_REQUEST_TIMEOUT_MS: 10 * 1000, // 10 seconds
  MIN_ENTROPY_UNIQUE_CHARS: 20, // Minimum unique characters for good entropy
} as const;

export const HTTP_CONSTANTS = {
  REQUEST_TIMEOUT_MS: 30000, // 30 seconds
  RETRY_MAX_ATTEMPTS: 3,
  RETRY_BASE_DELAY_MS: 1000,
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: 5,
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: 60000, // 1 minute
  CIRCUIT_BREAKER_MONITORING_PERIOD_MS: 10000, // 10 seconds
} as const;

export const INTEGRATION_CONSTANTS = {
  DEFAULT_BATCH_SIZE: 100,
  MAX_CONCURRENT_INTEGRATIONS: 5,
  SYNC_ID_LENGTH: 9,
} as const;

export const VALIDATION_CONSTANTS = {
  EMAIL_REGEX: /^[\w\-.]+@([\w-]+\.)+[\w-]{2,4}$/,
  MAX_STRING_LENGTH: 1000,
  MAX_ARRAY_LENGTH: 1000,
} as const;

export const ERROR_CODES = {
  AUTH_FAILED: 'AUTH_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONFIG_INVALID: 'CONFIG_INVALID',
  SYNC_FAILED: 'SYNC_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;
