// src/blueprint/schema/questionnaire.ts
export const QUESTIONNAIRE: readonly { path: string; question: string }[] = [
  { path: 'metadata.customerRef', question: 'What opaque reference identifies this customer engagement (never the legal name)?' },
  { path: 'goals', question: 'What must be true for the customer to call this integration a success, and how will each criterion be measured?' },
  { path: 'systems', question: 'Which commerce, ERP, payment, fulfillment, tax, and ancillary systems hold the data? Vendor, edition, API version, authentication model?' },
  { path: 'integrationPaths', question: 'Which integrations already move this data, who owns each (native connector, partner, customer-built, iPaaS), and what role should Squire play above them?' },
  { path: 'objects', question: 'Which business objects and API resources are in scope, and what are their key fields?' },
  { path: 'ownership', question: 'Which system owns each entity and field, who consumes it, and what happens on conflict?' },
  { path: 'mappings', question: 'Which field mappings and transformations are required, and which sample records prove them?' },
  { path: 'transformations', question: 'Which business rules must run during transformation?' },
  { path: 'exceptions', question: 'Which order-to-cash failures occur today, how often, how costly, and how are they handled?' },
  { path: 'approvals', question: 'Who may request a correction, who may approve it, and how many approvers are required?' },
  { path: 'dlp', question: 'Which fields are sensitive, and may personal data reach an AI provider?' },
  { path: 'testPlan', question: 'What evidence is available now (fixtures, dev store, sandbox, read-only access), and what tolerances define a tie-out?' },
  { path: 'adapterRequirements', question: 'Which vendor capabilities and scopes must each adapter have?' },
  { path: 'architecture', question: 'How will Squire observe, reconcile, explain, and propose across these systems?' },
  { path: 'backlog', question: 'What are the phases, gates, and estimates?' },
  { path: 'risks', question: 'What could stop this, and what is the mitigation?' },
  { path: 'blockers', question: 'What is unresolved and who owns it?' },
  { path: 'openQuestions', question: 'What is still unknown?' },
  { path: 'exclusions', question: 'What is explicitly out of scope for this Blueprint?' },
  { path: 'proposalInputs', question: 'Which phases, pricing basis, and statement-of-work sections belong in the proposal?' },
  { path: 'outcomes', question: 'Which outcomes would the customer accept as independently verifiable, and how is Squire’s contribution attributed?' },
];
